# Generated by Django 5.2.3 on 2025-06-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0002_alter_folder_created_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folder',
            name='access_type',
            field=models.CharField(choices=[('private', 'Private (Only Me)'), ('public', 'Public (Everyone in Company)'), ('group', 'Group Access')], default='private', help_text='Who can access this folder', max_length=10),
        ),
        migrations.AlterField(
            model_name='folder',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Required only for group access', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent_folder', 'access_type', 'group')},
        ),
    ]
