# Generated by Django 5.2.3 on 2025-06-14 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('filemanager', '0003_alter_folder_unique_together_folder_access_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('access_type', 'group')), fields=('name', 'parent_folder', 'access_type', 'group'), name='unique_group_folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('access_type', 'private')), fields=('name', 'parent_folder', 'access_type'), name='unique_private_folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('access_type', 'public')), fields=('name', 'parent_folder', 'access_type'), name='unique_public_folder'),
        ),
    ]
